### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-2-entrevista-entrevista-ar#2]
[ENTREVISTA_1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-entrevista-ar/files/9529779/ENTREVISTA_1.pdf)

**Comment by Abraham890** [comment]
Calificación: 20 puntos

**Comment by josealfredo79** [comment]
La conclusion es de 12 líneas... @Abraham890 por favor debes evaluar correctamente...

**Comment by josealfredo79** [comment]
Calificacion real 17
